version: "3.9"

services:

  ollama:
    image: ollama/ollama
    container_name: ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    restart: always

  backend:
    build: ./backend
    container_name: ai-backend
    ports:
      - "8000:8000"
    depends_on:
      - ollama
    volumes:
      - ./backend/chroma_db:/app/chroma_db
    environment:
      - OLLAMA_HOST=http://ollama:11434
    restart: always

volumes:
  ollama_data:
